### ISSUE TITLE
'float' object is not subscriptable"

### ISSUE THREAD

**Issue by birm** [choosehappy/HistoQC#134]
Ran without modifications, running in the python:3-stretch docker container.

```
2019-05-06 22:08:10,702 - INFO - no display found. Using non-interactive Agg backend
2019-05-06 22:08:11,899 - WARNING - Configuration file not set (--config), using default: /var/www/HistoQC/config.ini
2019-05-06 22:08:11,902 - INFO - Pipeline will use these steps:
2019-05-06 22:08:11,903 - INFO - 		BasicModule	getBasicStats
2019-05-06 22:08:12,267 - INFO - 		ClassificationModule	byExampleWithFeatures:coverslip_edge
2019-05-06 22:08:12,402 - INFO - 		LightDarkModule	getIntensityThresholdPercent:tissue
2019-05-06 22:08:12,404 - INFO - 		LightDarkModule	getIntensityThresholdPercent:darktissue
2019-05-06 22:08:12,404 - INFO - 		BubbleRegionByRegion	detectSmoothness
2019-05-06 22:08:12,406 - INFO - 		MorphologyModule	removeFatlikeTissue
2019-05-06 22:08:12,408 - INFO - 		MorphologyModule	fillSmallHoles
2019-05-06 22:08:12,408 - INFO - 		MorphologyModule	removeSmallObjects
2019-05-06 22:08:12,409 - INFO - 		BlurDetectionModule	identifyBlurryRegions
2019-05-06 22:08:12,410 - INFO - 		BasicModule	finalProcessingSpur
2019-05-06 22:08:12,411 - INFO - 		BasicModule	finalProcessingArea
2019-05-06 22:08:12,411 - INFO - 		HistogramModule	compareToTemplates
2019-05-06 22:08:12,413 - INFO - 		HistogramModule	getHistogram
2019-05-06 22:08:12,414 - INFO - 		BrightContrastModule	getContrast
2019-05-06 22:08:12,415 - INFO - 		BrightContrastModule	getBrightnessGray
2019-05-06 22:08:12,415 - INFO - 		BrightContrastModule	getBrightnessByChannelinColorSpace:RGB
2019-05-06 22:08:12,416 - INFO - 		BrightContrastModule	getBrightnessByChannelinColorSpace:YUV
2019-05-06 22:08:12,417 - INFO - 		DeconvolutionModule	seperateStains
2019-05-06 22:08:12,418 - INFO - 		SaveModule	saveFinalMask
2019-05-06 22:08:12,419 - INFO - 		SaveModule	saveThumbnails
2019-05-06 22:08:12,420 - INFO - 		BasicModule	finalComputations
2019-05-06 22:08:12,420 - INFO - ----------
2019-05-06 22:08:12,421 - INFO - Number of files detected by pattern:	1
2019-05-06 22:08:12,422 - INFO - -----Working on:	/images/apply.svs		1 of 1
2019-05-06 22:08:12,458 - INFO - apply.svs - 	getMag
2019-05-06 22:08:15,450 - INFO - apply.svs - 	getBasicStats
2019-05-06 22:08:15,450 - INFO - apply.svs - 	ClassificationModule.byExample:	coverslip_edge
2019-05-06 22:08:15,453 - INFO - apply.svs - Training model ClassificationModule.byExample:coverslip_edge
2019-05-06 22:08:15,489 - ERROR - /images/apply.svs - 	 - Error analyzing file (skipping): 	 <class 'TypeError'> Inappropriate argument type. ("'float' object is not subscriptable", '/images/apply.svs', '<code object byExampleWithFeatures at 0x7fdde4d93e40, file "/var/www/HistoQC/ClassificationModule.py", line 143>')
2019-05-06 22:08:15,496 - INFO - ------------Done---------

2019-05-06 22:08:15,496 - INFO - These images failed (available also in error.log), warnings are listed in warnings column in output:
2019-05-06 22:08:15,496 - INFO - /images/apply.svs	<class 'TypeError'> Inappropriate argument type. ("'float' object is not subscriptable", '/images/apply.svs', '<code object byExampleWithFeatures at 0x7fdde4d93e40, file "/var/www/HistoQC/ClassificationModule.py", line 143>')
2019-05-06 22:08:15,497 - INFO - Symlink to output directory created
```

**Comment by choosehappy** [comment]
does that issue present with different files/types or just this one?

e.g. do these  "generic" svs files work:  http://histoqcrepo.com/

**Comment by ragh1975** [comment]
I am seeing the same error. Does anyone know how to fix this?

**Comment by choosehappy** [comment]
does the error exist with the files provided at that URL?

Can you figure out which line the error is occurring on?

What does your configuration file look like?

**Comment by ragh1975** [comment]
It is happening in this code; I am using the default config.ini file that I download from the repo

2019-05-10 14:18:25,731 - ERROR - C:\temp\GO29436_226_1_302786_HE_279819004.svs -        - Error analyzing file (skipping):      <class 'TypeError'> Inappropriate argument type. ("'float' object is not subscriptable", 'C:\\temp\\GO29436_226_1_302786_HE_279819004.svs', '<code object byExampleWithFeatures at 0x142D0C28, file "C:\\Projects\\HistoQC-master\\ClassificationModule.py", line 143>')
2019-05-10 14:18:26,490 - INFO - ------------Done---------

**Comment by choosehappy** [comment]
line 143 is the function definition, not the line that is causing the error:

https://github.com/choosehappy/HistoQC/blob/7f925d488ea4a7eb94c9f6a026b1778cce448be7/ClassificationModule.py#L143

**Comment by choosehappy** [comment]
i've just tried it again locally and it seems to be okay, so i suspect it
is a library/version difference

what version of python are you using?

what is the output from pip freeze?

**Comment by ragh1975** [comment]
Python version is  3.7.3; I am new to pip, so not sure what you mean by pip freeze

**Comment by ragh1975** [comment]
I also tried with an image from the HistoQCRepo; same error

**Comment by ragh1975** [comment]
Here are all the libraries from pip freeze

cycler==0.10.0
decorator==4.4.0
imageio==2.5.0
joblib==0.13.2
kiwisolver==1.1.0
matplotlib==3.0.3
networkx==2.3
numpy==1.16.3
openslide-python==1.1.1
Pillow==6.0.0
pyparsing==2.4.0
python-dateutil==2.8.0
PyWavelets==1.0.3
scikit-image==0.15.0
scikit-learn==0.21.0
scipy==1.2.1
six==1.12.0
sklearn==0.0

**Comment by choosehappy** [comment]
https://pip.pypa.io/en/stable/reference/pip_freeze/

**Comment by choosehappy** [comment]
well it is definitely a version issue, the core works on both a linux and a
windows machine

i can try to recreate your environment in the coming days, but if you're
feeling adventurous you can clone my environment

i'm using python 3.7.1

and this requirements file (all of which are different versions than you
have):

cycler==0.10.0
decorator==4.3.2
matplotlib==3.0.2
networkx==2.2
numpy==1.16.1
openslide-python==1.1.1
Pillow==5.4.1
pyparsing==2.3.1
python-dateutil==2.8.0
PyWavelets==1.0.1
scikit-image==0.14.2
scikit-learn==0.20.2
scipy==1.2.1
six==1.12.0
sklearn==0.0

which you can install like so:

pip install -r requirements.txt

**Comment by ragh1975** [comment]
did that; getting a different error now (out of memory). I have Windows 10 64-bit with 16 GB of RAM

2019-05-10 16:57:44,077 - ERROR - <code object byExampleWithFeatures at 0x13894230, file "C:\Projects\HistoQC-master\ClassificationModule.py", line 143> -       - Error analyzing file (skipping):      <class 'MemoryError'> Out of memory. ('C:\\temp\\CMU-2_1_2.svs', '<code object byExampleWithFeatures at 0x13894230, file "C:\\Projects\\HistoQC-master\\ClassificationModule.py", line 143>')
2019-05-10 16:57:44,300 - INFO - ------------Done---------

2019-05-10 16:57:44,300 - INFO - These images failed (available also in error.log), warnings are listed in warnings column in output:
2019-05-10 16:57:44,301 - INFO - <code object byExampleWithFeatures at 0x13894230, file "C:\Projects\HistoQC-master\ClassificationModule.py", line 143> <class 'MemoryError'> Out of memory. ('C:\\temp\\CMU-2_1_2.svs', '<code object byExampleWithFeatures at 0x13894230, file "C:\\Projects\\HistoQC-master\\ClassificationModule.py", line 143>')

**Comment by choosehappy** [comment]
okay, using your python version + libraries, i'm able to reproduce the problem

**Comment by choosehappy** [comment]
error caused by a difference between this version of frangi filter in skimage:

https://scikit-image.org/docs/dev/api/skimage.filters.html#skimage.filters.frangi

and this version:

https://scikit-image.org/docs/0.14.x/api/skimage.filters.html#frangi

requirements now has >=.15 for skimage

**Comment by ragh1975** [comment]
For the out of memory issue, do I need to run with 64-bit Python?

**Comment by choosehappy** [comment]
oh right, sorry

what is the size of the image in both pixels and MB?

when running the app, does 100% of the ram become occupied during its
execution?

if not i suspect it is an issue with 32 bits, is there some reason to not
use 64 bits if possible?

**Comment by ragh1975** [comment]
When I try with 32-bit Python, I get out of memory error. I uninstalled and
installed 64-bit Python and now it is unable to call Skimage even though it
has been installed; see the error message below. When I open python and
then try to manually call import skimage.io, it works fine. Please help

I am running the following command from the HistoQC folder

python qc_pipeline.py -c config.ini -n 1 C:\temp\*.svs -o C:\temp\SVS
--symlinkoff --force

ERROR messages

2019-05-11 09:11:02,749 - INFO - Pipeline will use these steps:
2019-05-11 09:11:02,749 - INFO -                BasicModule
getBasicStats
Traceback (most recent call last):
  File "qc_pipeline.py", line 120, in load_pipeline
    mod = import_module(mod_name)
  File
"C:\Users\venugor2\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py",
line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in
_call_with_frames_removed
  File "C:\Projects\HistoQC-master\BasicModule.py", line 4, in <module>
    import skimage.io, skimage.color
  File
"C:\Users\venugor2\AppData\Local\Programs\Python\Python37\lib\site-packages\skimage\__init__.py",
line 177, in <module>
    from .data import data_dir
  File
"C:\Users\venugor2\AppData\Local\Programs\Python\Python37\lib\site-packages\skimage\data\__init__.py",
line 18, in <module>
    from ._binary_blobs import binary_blobs
  File
"C:\Users\venugor2\AppData\Local\Programs\Python\Python37\lib\site-packages\skimage\data\_binary_blobs.py",
line 2, in <module>
    from ..filters import gaussian
  File
"C:\Users\venugor2\AppData\Local\Programs\Python\Python37\lib\site-packages\skimage\filters\__init__.py",
line 3, in <module>
    from .edges import (sobel, sobel_h, sobel_v,
  File
"C:\Users\venugor2\AppData\Local\Programs\Python\Python37\lib\site-packages\skimage\filters\edges.py",
line 17, in <module>
    from ..restoration.uft import laplacian
  File
"C:\Users\venugor2\AppData\Local\Programs\Python\Python37\lib\site-packages\skimage\restoration\__init__.py",
line 8, in <module>
    from ._denoise import (denoise_tv_chambolle, denoise_tv_bregman,
  File
"C:\Users\venugor2\AppData\Local\Programs\Python\Python37\lib\site-packages\skimage\restoration\_denoise.py",
line 8, in <module>
    import pywt
  File
"C:\Users\venugor2\AppData\Roaming\Python\Python37\site-packages\pywt\__init__.py",
line 16, in <module>
    from ._extensions._pywt import *
ModuleNotFoundError: No module named 'pywt._extensions._pywt'

**Comment by choosehappy** [comment]
hmmm not really sure. this is quite difficult to debug remotely as it is
something inherently wrong with your installation of python

i wouldn't be surprised if switching from the 32 to 64 bit versions left
behind enough "stuff" that things didn't work

is it possible to try it on a different machine or under a different user
on the windows machine you're using ?

namely, recreate the python environment from scratch. perhaps using a
python virtualenv is sufficient? https://virtualenv.pypa.io/en/latest/

**Comment by ragh1975** [comment]
Do you have Docker container for this? It may be easier to deploy that
instead of wrangling with the library versions

**Comment by ragh1975** [comment]
I installed Python 3.6.6; it nows moves further in the processing pipeline.
I am getting this error now; am I missing a library?

2019-05-13 10:25:25,143 - ERROR - C:\temp\CMU-2_1_2.svs -        - Error
analyzing file (skipping):      <class 'NameError'> Name not found
globally. ("name 'io' is not defined", 'C:\\temp\\CMU-2_1_2.svs', '<code
object finalProcessingSpur at 0x0000025E46429AE0, file
"C:\\Projects\\HistoQC-master\\BasicModule.py", line 27>')

**Comment by choosehappy** [comment]
unfortunately i don't have one ready, but can add it to the todo list for
later

that said, i had made one yesterday to test your environment and it worked
easily via the following steps:

1) start an empty ubuntu container
2) apt-get install openslide-tools
3) install python via e.g.,
https://tecadmin.net/install-python-3-7-on-ubuntu-linuxmint/
4) clone histoqc
5) pip install -r requirements.txt
6) use histoqc

**Comment by ragh1975** [comment]
Thanks. When I finish running the QC pipeline code, how do I know if the
Image passed QC? Or is that left to the user to figure out based on the
quantitative outputs?

**Comment by choosehappy** [comment]
the latter part is correct.

it needs to be left to the user because we've found that what "is" and
"isn't" acceptable depends highly on the specific use case being addressed

usually this is pretty easy, look at the slides which are +/- 1 or 2 std
deviation from the mean and you'll see where to focus your QC efforts

**Comment by ragh1975** [comment]
Thanks. On some of the SVS images, I am getting this error; do you know why
this would happen and how to fix this?

2019-05-13 14:22:53,156 - INFO - W:\GO29436_1320_2_413279_HE_282048025.svs
     <class 'ValueError'> Inappropriate argument value (of correct type).
('color kwarg must have one color per data set. 1 data sets and 3 colors
were provided', 'W:\\GO29436_1320_2_413279_HE_282048025.svs', '<code object
getHistogram at 0x0000018BD319D150, file
"C:\\Projects\\HistoQC-master\\HistogramModule.py", line 11>')

**Comment by choosehappy** [comment]
ahh!

its been a long time since i've seen that one.

can you share your image + config file?

if you look at the other thumbnails produced in that images output
directory, i think you'll find that as a result of the previous steps there
is no "good" tissue left in the mask

the error is caused by trying to compute a 3-dimensional histogram of an
empty vector.

i should print a warning to the screen and to the output file and skip the
rest of the function when this happens

**Comment by choosehappy** [comment]
Coming back to this, added a Dockerfile in a88d1902a3a3e282a97b4763c5696e22f267fa3c

**Comment by ragh1975** [comment]
Thanks
